force-app/main/default/objects/Account/fields/B_S_Referral_Source_Email__c.field-meta.xml
<CustomField>
    <fullName>B_S_Referral_Source_Email__c</fullName>
    <label>BS Referral Source Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/B_S_Referral_Source_Name__c.field-meta.xml
<CustomField>
    <fullName>B_S_Referral_Source_Name__c</fullName>
    <label>Referral Source Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/B_S_Referral_Source_surname__c.field-meta.xml
<CustomField>
    <fullName>B_S_Referral_Source_surname__c</fullName>
    <label>Referral Source surname</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/B_S_Referral_Source_Telephone__c.field-meta.xml
<CustomField>
    <fullName>B_S_Referral_Source_Telephone__c</fullName>
    <label>Referral Source Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/BS_Source_of_referral__c.field-meta.xml
<CustomField>
    <fullName>BS_Source_of_referral__c</fullName>
    <label>Source of referral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Health Nurse (PHN)</fullName>
            </value>
            <value>
                <fullName>Social Worker</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Email__c.field-meta.xml
<CustomField>
    <fullName>GFD_Email__c</fullName>
    <label>GFD Referral Source Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Professional_Title__c.field-meta.xml
<CustomField>
    <fullName>GFD_Professional_Title__c</fullName>
    <label>Professional Title</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Source_of_referral__c.field-meta.xml
<CustomField>
    <fullName>GFD_Source_of_referral__c</fullName>
    <label>Source of referral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Health Nurse (PHN)</fullName>
            </value>
            <value>
                <fullName>Social Worker</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Source_of_referral_First_Name__c.field-meta.xml
<CustomField>
    <fullName>GFD_Source_of_referral_First_Name__c</fullName>
    <label>Source of referral First Name</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Source_of_referral_Surname__c.field-meta.xml
<CustomField>
    <fullName>GFD_Source_of_referral_Surname__c</fullName>
    <label>Source of referral Surname</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Telephone__c.field-meta.xml
<CustomField>
    <fullName>GFD_Telephone__c</fullName>
    <label>Telephone</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_BS_section_updated__c.field-meta.xml
<CustomField>
    <fullName>Is_BS_section_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is BS section updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_GFD_section_updated__c.field-meta.xml
<CustomField>
    <fullName>Is_GFD_section_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is GFD section updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Professional_Title__c.field-meta.xml
<CustomField>
    <fullName>Professional_Title__c</fullName>
    <label>Professional Title</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Occupation1__c.field-meta.xml
<CustomField>
    <fullName>Occupation1__c</fullName>
    <label>Referral Source</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Health Nurse (PHN)</fullName>
            </value>
            <value>
                <fullName>Social Worker</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Professional_Title__c.field-meta.xml
<CustomField>
    <fullName>Professional_Title__c</fullName>
    <label>Professional Title</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ClientRegistrationController.cls
public without sharing class ClientRegistrationController {
    @AuraEnabled(cacheable= true)
    public static List<String> getHseAreas(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }
    
    @AuraEnabled(cacheable= true)
    public static List<String> getGfdReferenceStatus(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }
    
    @AuraEnabled(cacheable= true)
    public static List<String> getBAndSReferenceStatus(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }
    
    @AuraEnabled(cacheable= true)
    public static List<String> getConsentBy(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }
    
    @AuraEnabled(cacheable= true)
    public static List<String> getServiceSelections(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }
    
       
    @AuraEnabled(cacheable= true)
    public static List<String> getMethodOfInvoicing(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }
    
    @AuraEnabled(cacheable= true)
    public static List<String> getOtherBefriendingAgencies(sObject objObject, string fieldName){
        return GeneralUtil.getSelectOptions(objObject, fieldName);
    }

    @AuraEnabled
    public static void saveClientDetails(Account clientRecord, string registrationType, String referringAgentEmail){
        try{
            Contact conToUpdate = [SELECT Id, AccountId, FirstName, LastName, Occupation1__c,
                                   Professional_Title__c, MobilePhone, Email FROM Contact WHERE Email =: referringAgentEmail AND RecordTypeId =: Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referring Agent').getRecordTypeId() LIMIT 1];
            
            clientRecord.RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId();
            if(registrationType == 'BefriendingAndSupport'){
                clientRecord.B_S_Referral_Source_Name__c = conToUpdate.FirstName;
                clientRecord.B_S_Referral_Source_surname__c = conToUpdate.LastName;
                clientRecord.Professional_Title__c = conToUpdate.Professional_Title__c;
                clientRecord.B_S_Referral_Source_Telephone__c = conToUpdate.MobilePhone;
                clientRecord.B_S_Referral_Source_Email__c = conToUpdate.Email;
                clientRecord.BS_Source_of_referral__c = conToUpdate.Occupation1__c;
				clientRecord.Is_BS_section_updated__c  = true;
            } else{
                clientRecord.GFD_Source_of_referral_First_Name__c  = conToUpdate.FirstName;
                clientRecord.GFD_Source_of_referral_Surname__c = conToUpdate.LastName;
                clientRecord.GFD_Professional_Title__c = conToUpdate.Professional_Title__c;
                clientRecord.GFD_Source_of_referral__c = conToUpdate.Occupation1__c;
                clientRecord.GFD_Telephone__c = conToUpdate.MobilePhone;
                clientRecord.GFD_Email__c = conToUpdate.Email;
                clientRecord.Is_GFD_section_updated__c = true;     
            }
            upsert clientRecord;
        
            //conToUpdate.AccountId = clientRecord.Id;
            //update conToUpdate;
            List<AccountContactRelation> conRel =[SELECT ContactId FROM AccountContactRelation WHERE AccountId =:clientRecord.Id AND ContactId=:conToUpdate.Id ];
            if(conRel.isEmpty()){
                AccountContactRelation nw = new AccountContactRelation();
                nw.AccountId = clientRecord.Id;
                nw.ContactId = conToUpdate.Id;
                upsert nw;
            }
        } catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }
    }
    
}