force-app/main/default/objects/Account/fields/BS_Source_of_referral__c.field-meta.xml
<CustomField>
    <fullName>BS_Source_of_referral__c</fullName>
    <label>Source of referral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Health Nurse (PHN)</fullName>
            </value>
            <value>
                <fullName>Social Worker</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Client_s_HSE_Area__c.field-meta.xml
<CustomField>
    <fullName>Client_s_HSE_Area__c</fullName>
    <label>Client&apos;s HSE Area</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CHO 6 Area 1 (Blackrock, Cabinteely Dalkey, Dun Laoghaire, Loughlinstown, Foxrock)</fullName>
            </value>
            <value>
                <fullName>CHO 6 Area 2 (Baggot Street, Balally, Ballinteer, Churchtown, Donnybrook, Dundrum, Leopardstown, Milltown, Ranelagh, Sallynoggin, Sandyford, Sandymount, Shankill, Stillorgan)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Consent_given_by__c.field-meta.xml
<CustomField>
    <fullName>Consent_given_by__c</fullName>
    <label>Consent given by</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Client</fullName>
            </value>
            <value>
                <fullName>Next of Kin (nok)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/GFD_Source_of_referral__c.field-meta.xml
<CustomField>
    <fullName>GFD_Source_of_referral__c</fullName>
    <label>Source of referral</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Public Health Nurse (PHN)</fullName>
            </value>
            <value>
                <fullName>Social Worker</fullName>
            </value>
            <value>
                <fullName>Occupational Therapist</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Is_BS_section_updated__c.field-meta.xml
<CustomField>
    <fullName>Is_BS_section_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is BS section updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Is_GFD_section_updated__c.field-meta.xml
<CustomField>
    <fullName>Is_GFD_section_updated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is GFD section updated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Method_of_invoicing__c.field-meta.xml
<CustomField>
    <fullName>Method_of_invoicing__c</fullName>
    <label>Method of invoicing</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Phone/ Email + Bank Card</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Service_Selection__c.field-meta.xml
<CustomField>
    <fullName>Service_Selection__c</fullName>
    <label>Service Selection</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Befriending &amp; Supports Visits</fullName>
            </value>
            <value>
                <fullName>Telephone Befriending Calls</fullName>
            </value>
            <value>
                <fullName>Covid-19 Emergency Supports</fullName>
            </value>
            <value>
                <fullName>Cultural Connections</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ClientRegistrationControllerTest.cls
@isTest(seeAllData = false)
public class ClientRegistrationControllerTest {
    @testSetup
    static void setupData(){
        Account testAccount = new Account(Name = 'test Account', RecordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('HH_Account').getRecordTypeId());
        insert testAccount;
        
        Contact testContact = new Contact(
            LastName = 'testContact',
            Email = 'test@test.com',
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referring Agent').getRecordTypeId()
        );
        insert testContact;
    }
    
    
    @isTest
    private static void getHseAreasTest(){
        test.startTest();
            List<String> values = ClientRegistrationController.getHseAreas(new Account(), 'Client_s_HSE_Area__c');
        test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    private static void getGfdReferenceStatusTest(){
        test.startTest();
            List<String> values = ClientRegistrationController.getGfdReferenceStatus(new Account(), 'GFD_Source_of_referral__c');
        test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    private static void getBAndSReferenceStatusTest(){
        test.startTest();
            List<String> values = ClientRegistrationController.getBAndSReferenceStatus(new Account(), 'BS_Source_of_referral__c');
        test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    private static void getConsentByTest(){
        test.startTest();
            List<String> values = ClientRegistrationController.getConsentBy(new Account(), 'Consent_given_by__c');
        test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    private static void getServiceSelectionsTest(){
        test.startTest();
            List<String> values = ClientRegistrationController.getServiceSelections(new Account(), 'Service_Selection__c');
        test.stopTest();
        System.assert(!values.isEmpty());
    }
    
       
    @isTest
    private static void getMethodOfInvoicingTest(){
        test.startTest();
            List<String> values = ClientRegistrationController.getMethodOfInvoicing(new Account(), 'Method_of_invoicing__c');
        test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    private static void saveClientDetailsBSTest(){
        Account testAcc = [SELECT Id, Is_BS_section_updated__c, Is_GFD_section_updated__c FROM Account LIMIT 1];
        Contact testContact  = [SELECT Id, Email FROM Contact LIMIT 1];
        test.startTest();
            try{
                ClientRegistrationController.saveClientDetails(testAcc, 'BefriendingAndSupport', testContact.Email);
            } catch(Exception e){
                system.debug('exception');
            }
        test.stopTest();
    }
    
    @isTest
    private static void saveClientDetailsGFDTest(){
        Account testAcc = [SELECT Id, Is_BS_section_updated__c, Is_GFD_section_updated__c FROM Account LIMIT 1];
        Contact testContact  = [SELECT Id, Email FROM Contact LIMIT 1];
        test.startTest();
            try{
                ClientRegistrationController.saveClientDetails(testAcc, 'GoodFoodDelivered', testContact.Email);
            } catch(Exception e){
                system.debug('exception');
            }
        test.stopTest();
    }
}