force-app/main/default/objects/Account/fields/Client_Surname__c.field-meta.xml
<CustomField>
    <fullName>Client_Surname__c</fullName>
    <label>Client Surname</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/D_O_B__c.field-meta.xml
<CustomField>
    <fullName>D_O_B__c</fullName>
    <label>D.O.B.</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Any_special_skills_hobbies_or_interests__c.field-meta.xml
<CustomField>
    <fullName>Any_special_skills_hobbies_or_interests__c</fullName>
    <label>Any special skills, hobbies or interests</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Music</fullName>
            </value>
            <value>
                <fullName>Gardening, Art</fullName>
            </value>
            <value>
                <fullName>Theatre</fullName>
            </value>
            <value>
                <fullName>Reading</fullName>
            </value>
            <value>
                <fullName>Dancing</fullName>
            </value>
            <value>
                <fullName>Sports</fullName>
            </value>
            <value>
                <fullName>Current Affairs</fullName>
            </value>
            <value>
                <fullName>History</fullName>
            </value>
            <value>
                <fullName>TV Shows</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Driving_Availability__c.field-meta.xml
<CustomField>
    <fullName>Driving_Availability__c</fullName>
    <label>Driving Availability</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monday</fullName>
            </value>
            <value>
                <fullName>Wednesday</fullName>
            </value>
            <value>
                <fullName>Friday</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/How_did_you_hear_about_MC__c.field-meta.xml
<CustomField>
    <fullName>How_did_you_hear_about_MC__c</fullName>
    <label>How did you hear about MC?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>i-vol</fullName>
            </value>
            <value>
                <fullName>Online search</fullName>
            </value>
            <value>
                <fullName>Newspaper</fullName>
            </value>
            <value>
                <fullName>Radio</fullName>
            </value>
            <value>
                <fullName>Someone I know is involved with Making Connection</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Infrequent_news_or_events_from_MC__c.field-meta.xml
<CustomField>
    <fullName>Infrequent_news_or_events_from_MC__c</fullName>
    <label>Infrequent news or events from MC</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Email</fullName>
            </value>
            <value>
                <fullName>Phone</fullName>
            </value>
            <value>
                <fullName>Post</fullName>
            </value>
            <value>
                <fullName>I don’t want to hear about other news/ events</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Reference_Status__c.field-meta.xml
<CustomField>
    <fullName>Reference_Status__c</fullName>
    <label>Reference Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending (default)</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Reference Calls Complete</fullName>
            </value>
            <value>
                <fullName>Reviewed - Approved</fullName>
            </value>
            <value>
                <fullName>Reviewed - Not Eligible</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Registration_Form_submitted__c.field-meta.xml
<CustomField>
    <fullName>Registration_Form_submitted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Registration Form submitted?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Volunteer.recordType-meta.xml
<RecordType>
    <fullName>Volunteer</fullName>
    <active>true</active>
    <label>Volunteer</label>
</RecordType>

force-app/main/default/classes/RegistrationFormControllerTest.cls
@isTest(seeAllData = false)
public class RegistrationFormControllerTest {
	@TestSetup
    public static void setup(){
        Account testAccount = new Account(Name='Test Account', D_O_B__c=Date.today(), Client_Surname__c = 'Test');
        insert testAccount;
        
        Contact testContact = new Contact(
        	LastName = 'Test',
            Email = 'Test@test.com',
            AccountId = testAccount.Id
        );
        insert testContact;
        
        Contact reffAgentContact = new Contact(
        	LastName = 'Test',
            Email = 'Test@test1.com',
            AccountId = testAccount.Id,
            RecordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Referring Agent').getRecordTypeId()
        );
        insert reffAgentContact;
    }
    
    @isTest
    public static void authorizeRegistrationVolunteerTest(){
        Contact testContact = [SELECT Id, Email FROM Contact WHERE Email = 'Test@test.com' LIMIT 1];
        List<Contact> con = new List<Contact>();
        Test.startTest();
        	con.add((Contact)RegistrationFormController.authorizeRegistration(testContact.Email, 'Volunteer'));
        Test.stopTest();
    }
    
    
    @isTest
    public static void authorizeRegistrationReferringAgentForClientTest(){
        Contact reffAgentContact = [SELECT Id, Email FROM Contact WHERE Email = 'Test@test1.com' LIMIT 1];
        List<Contact> con = new List<Contact>();
        Test.startTest();
        	con.add((Contact)RegistrationFormController.authorizeRegistration(reffAgentContact.Email, 'ReferringAgentforClient'));
        Test.stopTest();
    }
    
    @isTest
    public static void getInterestPicklistValuesTest(){
        Test.startTest();
        	List<String> values = RegistrationFormController.getInterestPicklistValues(new Contact(), 'Any_special_skills_hobbies_or_interests__c');
        Test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    public static void getReferenceStatusValuesTest(){
        Test.startTest();
        	List<String> values = RegistrationFormController.getReferenceStatusValues(new Contact(), 'Reference_Status__c');
        Test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    public static void getSourceOfMakingConnectionsTest(){
        Test.startTest();
        	List<String> values = RegistrationFormController.getSourceOfMakingConnections(new Contact(), 'How_did_you_hear_about_MC__c');
        Test.stopTest();
		System.assert(!values.isEmpty());
    }
    
    @isTest
    public static void getCommunicationMethodsTest(){
        Test.startTest();
        	List<String> values = RegistrationFormController.getDrivingDays(new Contact(), 'Infrequent_news_or_events_from_MC__c');
        Test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    
    @isTest
    public static void getDrivingDaysTest(){
        Test.startTest();
        	List<String> values = RegistrationFormController.getCommunicationMethods(new Contact(), 'Driving_Availability__c');
        Test.stopTest();
        System.assert(!values.isEmpty());
    }
    
    @isTest
    public static void updateContactRecordDetailsGFDTest(){
		Contact testContact = [SELECT Id, Email, Registration_Form_submitted__c FROM Contact LIMIT 1];
        Test.startTest();
        RegistrationFormController.updateContactRecordDetails(testContact, 'Contact', new List<String>{'GoodFoodDelivered'});
        Test.stopTest();
        Contact updatedContact = [SELECT Id, Email, Registration_Form_submitted__c FROM Contact WHERE Id =: testContact.Id];
        System.assertEquals(true, updatedContact.Registration_Form_submitted__c, 'Asert if value is updated');
    }
    
    @isTest
    public static void updateContactRecordDetailsBFTest(){
		Contact testContact = [SELECT Id, Email, Registration_Form_submitted__c FROM Contact LIMIT 1];
        Test.startTest();
        RegistrationFormController.updateContactRecordDetails(testContact, 'Contact', new List<String>{'BefriendingAndSupport'});
        Test.stopTest();
        Contact updatedContact = [SELECT Id, Email, Registration_Form_submitted__c FROM Contact WHERE Id =: testContact.Id];
        System.assertEquals(true, updatedContact.Registration_Form_submitted__c, 'Asert if value is updated');
    }
    
    @isTest
    public static void updateContactRecordDetailsBFAndGfdTest(){
		Contact testContact = [SELECT Id, Email, Registration_Form_submitted__c FROM Contact LIMIT 1];
        Test.startTest();
        RegistrationFormController.updateContactRecordDetails(testContact, 'Contact', new List<String>{'BefriendingAndSupport', 'GoodFoodDelivered'});
        Test.stopTest();
        Contact updatedContact = [SELECT Id, Email, Registration_Form_submitted__c FROM Contact WHERE Id =: testContact.Id];
        System.assertEquals(true, updatedContact.Registration_Form_submitted__c, 'Asert if value is updated');
    }
    
}