force-app/main/default/objects/Lead/fields/Volunteer_Opportunities__c.field-meta.xml
<CustomField>
    <fullName>Volunteer_Opportunities__c</fullName>
    <label>Volunteer Opportunities</label>
    <required>true</required>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Volunteer Befriending</fullName>
            </value>
            <value>
                <fullName>Volunteer Driver (meal delivery)</fullName>
            </value>
            <value>
                <fullName>Fundraising</fullName>
            </value>
            <value>
                <fullName>Short Term Tasks/ Projects</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/VolunteerExpressionController.cls
public with sharing class VolunteerExpressionController {
    @AuraEnabled
    public static void createLeadVolunteer(Lead leadRecord){
        try {
            leadRecord.Active__c = 'Active';
            insert leadRecord;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
    
    @AuraEnabled
    public static List<String> getPicklistValues(){
        List <String> options= new List <String>();
        Schema.SObjectType s = Schema.getGlobalDescribe().get('Lead') ;
        Schema.DescribeSObjectResult r = s.getDescribe() ;
        Map<String,Schema.SObjectField> fields = r.fields.getMap() ;
        Schema.DescribeFieldResult fieldResult = fields.get('Volunteer_Opportunities__c').getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        for( Schema.PicklistEntry pickListVal : ple){
            options.add(pickListVal.getValue());
        } 
        return options;
    }
}